- StatusBar isn't responsive with themes yet, let it black for both.
ComunidadeDevSpace/FitSpace pull request #34
Opened 2023-10-24 16:58 UTC by Serginho6

- SettingsFragment now has icons responsive to selected theme.
- SiginIn materialCardviews margin fixed

2023-10-24 17:58 UTC, jbalves requested changes
favor verificar a viabilidade de utilizar Viewbindig

2023-10-24 17:58 UTC, jbalves commented on app/src/main/java/com/app/fitspace/presentation/fragment/SettingsFragment.kt
> +        val profileIcon: ImageView = view.findViewById(R.id.image_view_item_profile)
o que você acha de utilizarmos Viewbinding para acessar esses componentes de UI ?

2023-10-24 18:22 UTC, Serginho6 commented on app/src/main/java/com/app/fitspace/presentation/fragment/SettingsFragment.kt
> +        val profileIcon: ImageView = view.findViewById(R.id.image_view_item_profile)
Fiz a refatoração da SettingsFragment e do HomeFragment para utilizar o Viewbinding.

2023-10-25 02:50 UTC, jbalves approved these changes
Great Job!

2023-10-25 12:25 UTC, merged